# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52e1172de5d1a2d2a31102a33113ef187ea79e48e6b849364b047145c731537f751b60efb1b534b8bc98bff317cf336e755ba0520fa2141e119cba8f7268b992
  secret_key_base: here_goes_my_secret_key_base
  google_client_id: 200645772058-8flo5ba901tiqdrkpss73nqb9qe2e4ph.apps.googleusercontent.com
  google_client_secret: bZWjTCISBWZO0YqGcUvx30Hc

test:
  secret_key_base: 0ba6a5ff5946a7af6163f152109e0dab06c8cdfc4369e4b1eee599a09ece0385c02a1ce7021a59b87be5447bcd90a77c232f29d6db5aa660f69780b8fcc12420

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
